Docstring updates
adafruit/Adafruit_CircuitPython_FunHouse pull request #13
Opened 2021-05-16 22:33 UTC by joezilla86

Corrected typo in pressure doc string
Added units of measure to temperature, pressure, relative_humidity properties

2021-05-16 23:12 UTC, jposada202020 requested changes
Before submitting the pull request, make sure you've run Pylint and Black locally on your code. You can do this manually or using pre-commit. Instructions are available here: https://adafru.it/check-your-code

2021-05-16 23:12 UTC, jposada202020 commented on adafruit_funhouse/peripherals.py
> +        Return the temperature in degrees Celcius
This should be `Celsius`

2021-05-16 23:25 UTC, jposada202020 commented
Thanks :)

2021-05-17 00:58 UTC, joezilla86 commented on adafruit_funhouse/peripherals.py
> +        Return the temperature in degrees Celcius
Fixed

2021-05-17 01:12 UTC, jposada202020 commented
Thanks for your Contribution

2021-05-17 01:12 UTC, merged